# Backend Dockerfile
FROM node:22

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./ 
RUN npm install

# Copy everything (including master and slave folders)
COPY . .

# Set entry point to master/server.js
CMD ["node", "master/server.js"]
