# Backend Dockerfile
FROM node:22

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./ 
RUN npm install

RUN npm install -g nodemon

# Copy everything (including master and slave folders)
COPY . .

# Set entry point to master/server.js
CMD ["npm","run","dev"]


#$ docker run -it -p 5000:5000 -v "C:/Users/Hp/Desktop/CodeKAR/backend:/app" backend

